import { BadgeType, FeatureItem } from "./types";

export const RAW_FEATURES: FeatureItem[] = [
  {
    id: "qibla",
    label: "Qibla Direction",
    subtitle: "Precise Kaaba direction using device sensors",
    route: "/(protected)/(pages)/additional-features/kaaba-direction",
    icon: { name: "compass-outline", set: "ion" },
    badge: "NEW",
    tint: "#00B894",
    highlight: true,
    locked: false,
    tags: [
      "qibla",
      "kaaba",
      "direction",
      "compass",
      "islam",
      "navigation",
      "location",
      "faith",
      "mecca",
      "muslim utility",
    ],
  },
  {
    id: "prayer-times",
    label: "Prayer Times",
    subtitle: "Daily salah schedule with offline and online modes",
    route: "/(protected)/(pages)/additional-features/prayer-times",
    icon: { name: "time-outline", set: "ion" },
    badge: "BETA",
    tint: "#6C5CE7",
    highlight: true,
    locked: false,
    tags: [
      "prayer",
      "namaz",
      "times",
      "adhan",
      "fajr",
      "islamic date",
      "muslim",
      "offline",
      "madhab",
      "timings",
    ],
  },
  {
    id: "tasbeeh",
    label: "Tasbeeh Counter",
    subtitle: "Smart dhikr counter with haptics & custom phrases",
    icon: { name: "infinite-outline", set: "ion" },
    badge: "SOON",
    route: "/(protected)/(pages)/additional-features/tasbeeh-counter",
    tint: "#FF7675",
    locked: true,
    tags: [
      "tasbeeh",
      "dhikr",
      "counter",
      "zikr",
      "subhanallah",
      "allahuakbar",
      "islamic",
      "praise",
      "spirituality",
      "remembrance",
    ],
  },
  {
    id: "hadith",
    label: "Hadith Bookmarks",
    subtitle: "Bookmark, tag, and revisit authentic Hadith",
    icon: { name: "book-outline", set: "ion" },
    badge: "SOON",
    tint: "#0984E3",
    locked: true,
    tags: [
      "hadith",
      "sunnah",
      "bookmark",
      "bukhari",
      "muslim",
      "islamic text",
      "reference",
      "learning",
      "tagging",
      "knowledge",
    ],
  },
  {
    id: "nearby-mosques",
    label: "Nearby Mosques",
    subtitle: "Find masjids near you, with map and distance",
    icon: { name: "mosque", set: "mci" },
    tint: "#55EFC4",
    badge: "SOON",
    route: "/(protected)/(pages)/additional-features/nearby-mosque",
    locked: true,
    tags: [
      "mosque",
      "masjid",
      "nearby",
      "location",
      "gps",
      "islam",
      "prayer place",
      "map",
      "distance",
      "community",
    ],
  },

  // 🔒 New Offline Features Below
  {
    id: "hijri-calendar",
    label: "Hijri Calendar",
    subtitle: "Islamic calendar with key events & today's Hijri date",
    icon: { name: "calendar-outline", set: "ion" },
    tint: "#FDCB6E", // warm gold
    locked: true,
    tags: [
      "hijri",
      "calendar",
      "islamic date",
      "events",
      "ramadan",
      "eid",
      "offline",
      "lunar",
    ],
  },
  {
    id: "verse-of-the-day",
    label: "Verse of the Day",
    subtitle: "Daily Ayah and Tafsir from offline Quran data",
    icon: { name: "book", set: "ion" },
    tint: "#74B9FF", // light blue
    route: "/(protected)/(pages)/additional-features/daily-verse",
    locked: true,
    tags: [
      "quran",
      "ayah",
      "verse",
      "tafsir",
      "spirituality",
      "reflection",
      "offline",
      "knowledge",
    ],
  },
  {
    id: "zakat-calculator",
    label: "Zakat Calculator",
    subtitle: "Calculate zakat anonymously, even offline",
    icon: { name: "calculator-outline", set: "ion" },
    tint: "#A29BFE", // light lavender
    badge: "BETA",
    route: "/(protected)/(pages)/additional-features/zakaat-calculator",
    highlight: true,
    locked: true,
    tags: [
      "zakat",
      "charity",
      "islam",
      "calculation",
      "nisab",
      "offline",
      "gold",
      "wealth",
    ],
  },
  {
    id: "fasting-tracker",
    label: "Fasting Tracker",
    subtitle: "Track Ramadan, Qadha and Sunnah fasts",
    icon: { name: "checkmark-done-outline", set: "ion" },
    tint: "#00CEC9", // tropical sea
    locked: true,
    route: "/(protected)/(pages)/additional-features/fasting-tracker",
    tags: [
      "fasting",
      "ramadan",
      "qadha",
      "sunnah",
      "tracker",
      "streaks",
      "offline",
      "islam",
    ],
  },
  {
    id: "fiqh-cards",
    label: "Fiqh Quick Cards",
    subtitle: "Swipe through essential Islamic rulings in seconds",
    icon: { name: "layers-outline", set: "ion" },
    route: "/(protected)/(pages)/additional-features/fiqh-cards",
    badge: "SOON",
    tint: "#81ECEC", // bright aqua
    locked: true,
    highlight: false,
    tags: [
      "fiqh",
      "rulings",
      "islamic law",
      "quick answers",
      "cards",
      "offline",
      "learning",
      "new muslim",
      "faq",
      "guidance",
    ],
  },
  {
    id: "sunnah-checklist",
    label: "Sunnah Checklist",
    subtitle: "Track daily Sunnah habits and personal growth",
    icon: { name: "checkbox-outline", set: "ion" },
    tint: "#FFEAA7", // soft yellow
    locked: true,
    tags: [
      "sunnah",
      "habit",
      "prophet",
      "practice",
      "tracker",
      "offline",
      "self improvement",
    ],
  },
  {
    id: "hijri-gregorian",
    label: "Date Converter",
    subtitle: "Convert dates between Hijri & Gregorian instantly",
    icon: { name: "repeat-outline", set: "ion" },
    tint: "#55EFC4", // mint green
    locked: true,
    route: "/(protected)/(pages)/additional-features/hijri-gregorian",
    tags: [
      "date",
      "hijri",
      "gregorian",
      "convert",
      "islamic calendar",
      "offline",
      "utility",
    ],
  },

  // MORE
  {
    id: "sadaqah-reminder",
    label: "Sadaqah Reminder",
    subtitle: "Gentle reminder to give charity daily or weekly",
    icon: { name: "heart-outline", set: "ion" },
    tint: "#E17055", // warm coral
    badge: "NEW",
    route: "/(protected)/(pages)/additional-features/sadaqah-reminder",
    highlight: true,
    locked: true,
    tags: [
      "sadaqah",
      "charity",
      "reminder",
      "donation",
      "habit",
      "good deeds",
      "offline",
      "faith",
      "muslim",
    ],
  },
  {
    id: "wudu-guide",
    label: "Wudu Guide",
    subtitle: "Step-by-step visual and audio guide for ablution",
    icon: { name: "water-outline", set: "ion" },
    tint: "#00CEC9", // teal
    badge: "BETA",
    route: "/(protected)/(pages)/additional-features/wudu-guide",
    highlight: false,
    locked: false,
    tags: [
      "wudu",
      "ablution",
      "guide",
      "learning",
      "islam",
      "new muslim",
      "offline",
      "purity",
      "steps",
    ],
  },
  {
    id: "halal-food-scanner",
    label: "Halal Food Scanner",
    subtitle: "Scan barcodes or ingredients to check Halal status",
    icon: { name: "barcode-outline", set: "ion" },
    tint: "#55EFC4", // mint green
    badge: "BETA",
    route: "/(protected)/(pages)/additional-features/halal-scanner",
    highlight: true,
    locked: true,
    tags: [
      "halal",
      "food",
      "scanner",
      "barcode",
      "ingredients",
      "diet",
      "utility",
      "online",
      "shopping",
    ],
  },
  {
    id: "islamic-encyclopedia",
    label: "Islamic Encyclopedia",
    subtitle: "Offline reference for key Islamic terms and concepts",
    icon: { name: "search-outline", set: "ion" },
    tint: "#A3CB38", // green yellow
    badge: "SOON",
    route: "/(protected)/(pages)/additional-features/islamic-encyclopedia",
    highlight: false,
    locked: true,
    tags: [
      "encyclopedia",
      "reference",
      "learning",
      "offline",
      "education",
      "islam",
      "knowledge",
      "terms",
    ],
  },
  {
    id: "islamic-names",
    label: "Islamic Baby Names",
    subtitle: "Search thousands of meaningful names and their origins.",
    icon: { name: "book-outline", set: "ion" }, // Changed to 'book-outline' to suggest a reference/list
    tint: "#27ae60", // A fresh, vibrant green
    route: "/(protected)/(pages)/additional-features/islamic-names",
    highlight: false,
    locked: true,
    badge: "NEW",
    tags: [
      "baby names",
      "muslim names",
      "meanings",
      "children",
      "family",
      "reference",
      "islam",
      "names",
    ],
  },
  {
    id: "shahada",
    // label: "The Shahada (Declaration of Faith)",
    label: "The Shahada",
    subtitle: "Read, memorize, and understand the first Pillar of Islam.",
    icon: { name: "create-outline", set: "ion" }, // 'create-outline' suggests writing, documenting, or making a declaration
    tint: "#3498db", // A peaceful and profound blue
    route: "/(protected)/(pages)/additional-features/shahada",
    highlight: true, // Marking it as important/new
    tags: [
      "shahada",
      "pillar of islam",
      "testimony",
      "creed",
      "tawhid",
      "islam",
      "faith",
      "reference",
    ],
  },
];

export const BADGE_STYLES: Record<
  NonNullable<BadgeType>,
  { bg: string; text: string }
> = {
  NEW: { bg: "#E3FCEF", text: "#0F9154" },
  BETA: { bg: "#E8EAF6", text: "#3F51B5" },
  SOON: { bg: "#FFF3E0", text: "#EF6C00" },
};
