import { BadgeType, FeatureItem } from "./types";

export const RAW_FEATURES: FeatureItem[] = [
  {
    id: "qibla",
    label: "Qibla Direction",
    subtitle: "Precise Kaaba direction using device sensors",
    route: "/(protected)/(pages)/additional-features/kaaba-direction",
    icon: { name: "compass-outline", set: "ion" },
    badge: "NEW",
    tint: "#00B894",
    highlight: true,
    locked: false,
    tags: [
      "qibla",
      "kaaba",
      "direction",
      "compass",
      "islam",
      "navigation",
      "location",
      "faith",
      "mecca",
      "muslim utility",
    ],
  },
  {
    id: "prayer-times",
    label: "Prayer Times",
    subtitle: "Daily salah schedule with offline and online modes",
    route: "/(protected)/(pages)/additional-features/prayer-times",
    icon: { name: "time-outline", set: "ion" },
    badge: "BETA",
    tint: "#6C5CE7",
    highlight: true,
    locked: false,
    tags: [
      "prayer",
      "namaz",
      "times",
      "adhan",
      "fajr",
      "islamic date",
      "muslim",
      "offline",
      "madhab",
      "timings",
    ],
  },
  {
    id: "tasbeeh",
    label: "Tasbeeh Counter",
    subtitle: "Smart dhikr counter with haptics & custom phrases",
    icon: { name: "infinite-outline", set: "ion" },
    badge: "SOON",
    route: "/(protected)/(pages)/additional-features/tasbeeh-counter",
    tint: "#FF7675",
    locked: false,
    tags: [
      "tasbeeh",
      "dhikr",
      "counter",
      "zikr",
      "subhanallah",
      "allahuakbar",
      "islamic",
      "praise",
      "spirituality",
      "remembrance",
    ],
  },
  {
    id: "hadith",
    label: "Hadith Bookmarks",
    subtitle: "Bookmark, tag, and revisit authentic Hadith",
    icon: { name: "book-outline", set: "ion" },
    badge: "SOON",
    tint: "#0984E3",
    locked: true,
    tags: [
      "hadith",
      "sunnah",
      "bookmark",
      "bukhari",
      "muslim",
      "islamic text",
      "reference",
      "learning",
      "tagging",
      "knowledge",
    ],
  },
  {
    id: "nearby-mosques",
    label: "Nearby Mosques",
    subtitle: "Find masjids near you, with map and distance",
    icon: { name: "mosque", set: "mci" },
    tint: "#55EFC4",
    badge: "SOON",
    locked: true,
    tags: [
      "mosque",
      "masjid",
      "nearby",
      "location",
      "gps",
      "islam",
      "prayer place",
      "map",
      "distance",
      "community",
    ],
  },

  // 🔒 New Offline Features Below
  {
    id: "hijri-calendar",
    label: "Hijri Calendar",
    subtitle: "Islamic calendar with key events & today's Hijri date",
    icon: { name: "calendar-outline", set: "ion" },
    tint: "#FDCB6E", // warm gold
    locked: true,
    tags: [
      "hijri",
      "calendar",
      "islamic date",
      "events",
      "ramadan",
      "eid",
      "offline",
      "lunar",
    ],
  },
  {
    id: "verse-of-the-day",
    label: "Verse of the Day",
    subtitle: "Daily Ayah and Tafsir from offline Quran data",
    icon: { name: "book", set: "ion" },
    tint: "#74B9FF", // light blue
    locked: true,
    tags: [
      "quran",
      "ayah",
      "verse",
      "tafsir",
      "spirituality",
      "reflection",
      "offline",
      "knowledge",
    ],
  },
  {
    id: "zakat-calculator",
    label: "Zakat Calculator",
    subtitle: "Calculate zakat anonymously, even offline",
    icon: { name: "calculator-outline", set: "ion" },
    tint: "#A29BFE", // light lavender
    badge: "BETA",
    route: "/(protected)/(pages)/additional-features/zakaat-calculator",
    highlight: true,
    tags: [
      "zakat",
      "charity",
      "islam",
      "calculation",
      "nisab",
      "offline",
      "gold",
      "wealth",
    ],
  },
  {
    id: "fasting-tracker",
    label: "Fasting Tracker",
    subtitle: "Track Ramadan, Qadha and Sunnah fasts",
    icon: { name: "checkmark-done-outline", set: "ion" },
    tint: "#00CEC9", // tropical sea
    locked: true,
    tags: [
      "fasting",
      "ramadan",
      "qadha",
      "sunnah",
      "tracker",
      "streaks",
      "offline",
      "islam",
    ],
  },
  {
    id: "fiqh-cards",
    label: "Fiqh Quick Cards",
    subtitle: "Swipe through essential Islamic rulings in seconds",
    icon: { name: "layers-outline", set: "ion" },
    route: "/(protected)/(pages)/additional-features/fiqh-cards",
    badge: "SOON",
    tint: "#81ECEC", // bright aqua
    locked: false,
    highlight: false,
    tags: [
      "fiqh",
      "rulings",
      "islamic law",
      "quick answers",
      "cards",
      "offline",
      "learning",
      "new muslim",
      "faq",
      "guidance",
    ],
  },
  {
    id: "islamic-names",
    label: "Islamic Names",
    subtitle: "5,000+ names with meanings and origins",
    icon: { name: "person-outline", set: "ion" },
    tint: "#FAB1A0", // peach
    locked: true,
    tags: [
      "names",
      "meaning",
      "baby names",
      "islamic",
      "reference",
      "offline",
      "roots",
    ],
  },
  {
    id: "sunnah-checklist",
    label: "Sunnah Checklist",
    subtitle: "Track daily Sunnah habits and personal growth",
    icon: { name: "checkbox-outline", set: "ion" },
    tint: "#FFEAA7", // soft yellow
    locked: true,
    tags: [
      "sunnah",
      "habit",
      "prophet",
      "practice",
      "tracker",
      "offline",
      "self improvement",
    ],
  },
  {
    id: "hijri-gregorian",
    label: "Date Converter",
    subtitle: "Convert dates between Hijri & Gregorian instantly",
    icon: { name: "repeat-outline", set: "ion" },
    tint: "#55EFC4", // mint green
    locked: false,
    route: "/(protected)/(pages)/additional-features/hijri-gregorian",
    tags: [
      "date",
      "hijri",
      "gregorian",
      "convert",
      "islamic calendar",
      "offline",
      "utility",
    ],
  },
];

export const BADGE_STYLES: Record<
  NonNullable<BadgeType>,
  { bg: string; text: string }
> = {
  NEW: { bg: "#E3FCEF", text: "#0F9154" },
  BETA: { bg: "#E8EAF6", text: "#3F51B5" },
  SOON: { bg: "#FFF3E0", text: "#EF6C00" },
};
